apiVersion: v1
kind: Service
metadata:
  name: gcs-fs-deployment
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: gcs-fs-service
        tier: frontend
    spec:
      containers:
      - name: gcs-fs
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        lifecycle:
          postStart:
            exec:
              command: ["gcsfuse", "-o", "nonempty", "sgsg-dm-fs", "/gcs/app_folder"]
          preStop:
            exec:
              command: ["fusermount", "-u", "/gcs/app_folder"]
        image: gcr.io/sgsg-dm/gcs-fs
        ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 8080

